name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Match the Python version in your Hatch config

      - name: Install Hatch
        run: pip install hatch

      - name: Install dependencies
        run: hatch env create  # Create and install dependencies in the Hatch environment

      - name: Run tests
        run: hatch run test  # Use the Hatch script to run tests