name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  pypi_release:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Match the Python version in your Hatch config

      - name: Install Hatch
        run: pip install hatch

      - name: Install dependencies
        run: hatch env create  # Create and install dependencies in the Hatch environment

      - name: Run tests
        run: hatch run test  # Run tests before publishing

      - name: Publish package
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: hatch build && hatch publish --repo pypi