name: Tox

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'docsrc/**'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'docsrc/**'

jobs:
  test:
    name: Run unit tests in tox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Match the Python version in your Hatch config

      - name: Install Hatch and Tox
        run: pip install hatch tox

      - name: Install dependencies
        run: hatch env create  # Create and install dependencies in the Hatch environment

      - name: Run all tox tests
        if: github.event_name != 'pull_request'
        run: tox

      - name: Run tox tests (fast only)
        if: github.event_name == 'pull_request'
        run: tox -- -k not slow